---
name: Post Merge

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build edge
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4.4.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1

      - name: Log in to the Container registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish docker plugin
        env:
          REPO: ghcr.io/${{ github.repository }}
          TAG_NAME: edge
        run: |-
          REPO=${{ env.REPO }} VERSION=${{ env.TAG_NAME }} make plugin
          docker plugin push "${{ env.REPO }}:${{ env.TAG_NAME }}-linux-amd64"
          docker plugin push "${{ env.REPO }}:${{ env.TAG_NAME }}-linux-arm64"
          docker plugin push "${{ env.REPO }}:${{ env.TAG_NAME }}-darwin-amd64"
          docker plugin push "${{ env.REPO }}:${{ env.TAG_NAME }}-darwin-arm64"
          docker plugin push "${{ env.REPO }}:${{ env.TAG_NAME }}-windows-amd64"
          docker plugin push "${{ env.REPO }}:${{ env.TAG_NAME }}"

          # docker does not currently support multi-arch plugins so we cannot create a list manifest
