---
name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set TAG_NAME in Environment
      # Subsequent jobs will be have the computed tag name
        run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish docker plugin
        env:
          REPO: ghcr.io/${{ github.repository }}
        run: |-
          REPO=${{ env.REPO }} VERSION=${{ env.TAG_NAME }} make plugin
          docker plugin push "${{ env.REPO }}:${{ env.TAG_NAME }}"
